"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Any=any;
function authHeaders(token:string){return {Authorization:`Bearer ${token}`}};
export default function Home(){
 const [token,setToken]=useState(""); const [authMode,setAuthMode]=useState<"login"|"register">("login"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState("");
 const [profiles,setProfiles]=useState<Any[]>([]),[apps,setApps]=useState<Any[]>([]); const [jd,setJd]=useState(""); const [cv,setCv]=useState<File|null>(null); const [analysis,setAnalysis]=useState<Any>(); const [answers,setAnswers]=useState<Any>({}); const [profileId,setProfileId]=useState<number>(); const [generation,setGeneration]=useState<Any>(); const [resume,setResume]=useState<Any>(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{const t=localStorage.getItem("cvforge_token");if(t)setToken(t)},[]);
 async function request(path:string,init:RequestInit={}){const r=await fetch(API+path,{...init,headers:{...(init.headers||{}),...(token?authHeaders(token):{})}});if(!r.ok)throw new Error(await r.text());return r.json()}
 async function auth(){setError("");try{const r=await fetch(`${API}/api/v1/auth/${authMode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,name})});if(!r.ok)throw new Error(await r.text());const x=await r.json();localStorage.setItem("cvforge_token",x.token);setToken(x.token)}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(token){request("/api/v1/profiles").then(setProfiles).catch(()=>{});request("/api/v1/applications").then(setApps).catch(()=>{})}},[token]);
 async function analyze(){setBusy(true);setError("");try{const f=new FormData();f.append("jd",jd);if(cv)f.append("cv",cv);setAnalysis(await request("/api/v1/jobs/analyze",{method:"POST",body:f}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function start(){setBusy(true);setError("");try{let pid=profileId;if(!pid){const f=new FormData();f.append("name",analysis.candidate.contact?.name||"Primary CV");if(cv)f.append("cv",cv);const p=await request("/api/v1/profiles",{method:"POST",body:f});pid=p.id;setProfileId(pid);setProfiles(await request("/api/v1/profiles"))}const a=await request("/api/v1/applications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({job:analysis.job,candidate_profile_id:pid,answers})});const g=await request(`/api/v1/jobs/enqueue?application_id=${a.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(answers)});setGeneration(g);setApps(await request("/api/v1/applications"));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(!generation?.generation_id)return;const timer=setInterval(async()=>{try{const s=await request(`/api/v1/jobs/${generation.generation_id}`);setGeneration((x:any)=>({...x,...s}));if(s.status==="completed"||s.status==="failed"){clearInterval(timer);if(s.status==="completed"){const a=await request(`/api/v1/applications/${s.application_id}`);const r=a.resumes[0];setResume(r)}}}catch{}},1500);return()=>clearInterval(timer)},[generation?.generation_id]);
 async function saveResume(){if(!resume)return;setBusy(true);try{const r=await request(`/api/v1/resumes/${resume.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({resume:resume.resume})});setResume(r)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!token)return <Auth mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} name={name} setName={setName} submit={auth} error={error}/>;
 return <main className="min-h-screen bg-neutral-50"><header className="border-b bg-white"><div className="mx-auto max-w-7xl px-6 py-5 flex justify-between"><div><b className="text-xl">CVForge</b><span className="ml-3 text-xs text-neutral-500">Evidence-first resume intelligence</span></div><button onClick={()=>{localStorage.removeItem("cvforge_token");setToken("")}} className="text-sm">Sign out</button></div></header><div className="mx-auto max-w-7xl p-6 grid lg:grid-cols-[260px_1fr] gap-6"><aside className="space-y-4"><div className="card"><h3 className="font-semibold">Saved CV profiles</h3>{profiles.map(p=><button key={p.id} onClick={()=>setProfileId(p.id)} className={`block w-full text-left mt-2 p-2 rounded-lg ${profileId===p.id?'bg-neutral-100':''}`}>{p.name}</button>)}<p className="text-xs text-neutral-500 mt-3">Profiles preserve your evidence so you don't re-upload your CV for every application.</p></div><div className="card"><h3 className="font-semibold">Applications</h3>{apps.map(a=><div key={a.id} className="mt-2 text-sm"><b>{a.job_title}</b><div className="text-xs text-neutral-500">{a.company||"—"} · {a.status}</div></div>)}</div></aside><section className="space-y-6"><div className="card"><h1 className="text-3xl font-semibold">Tailor a CV to one job.</h1><p className="mt-2 text-neutral-600">CVForge extracts evidence first, chooses a role/seniority/domain prompt, generates structured JSON with Grok, validates it deterministically, and lets you edit the final resume.</p><textarea value={jd} onChange={e=>setJd(e.target.value)} className="mt-5 w-full min-h-52 rounded-xl border p-4" placeholder="Paste the complete job description"/><div className="mt-4 flex gap-3 items-center"><input type="file" accept=".pdf,.docx,.txt,.md" onChange={e=>setCv(e.target.files?.[0]||null)}/><button disabled={!jd||busy} onClick={analyze} className="btn">{busy?"Working…":"Analyze JD + CV"}</button></div></div>
 {analysis&&<div className="grid md:grid-cols-2 gap-6"><div className="card"><h2 className="font-semibold">Role intelligence</h2><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><span>Title <b>{analysis.job.title}</b></span><span>Family <b>{analysis.job.role_family}</b></span><span>Level <b>{analysis.job.seniority}</b></span><span>Domain <b>{analysis.job.domain}</b></span></div><h3 className="mt-5 font-semibold">Required skills</h3><div className="flex flex-wrap gap-2 mt-2">{analysis.job.must_have_skills.map((x:string)=><span className="pill" key={x}>{x}</span>)}</div></div><div className="card"><h2 className="font-semibold">Evidence gaps</h2>{analysis.questions.length?analysis.questions.map((q:Any)=><div key={q.key} className="mt-4"><label className="text-sm font-medium">{q.question}</label><textarea className="mt-1 w-full rounded-xl border p-3" value={answers[q.key]||""} onChange={e=>setAnswers({...answers,[q.key]:e.target.value})} placeholder={q.reason}/></div>):<p className="mt-3 text-green-700">No additional evidence questions.</p>}<button onClick={start} disabled={busy} className="btn mt-5">{busy?"Starting generation…":"Generate tailored CV"}</button></div></div>}
 {generation&&<div className="card"><b>Generation status:</b> {generation.status}{generation.status==="running"||generation.status==="queued"?<p className="text-sm text-neutral-500 mt-2">Grok generation is running in the background. You can safely leave this page and return to the application.</p>:null}{generation.error&&<pre className="text-red-600 whitespace-pre-wrap mt-2">{generation.error}</pre>}</div>}
 {resume&&<Editor resume={resume} setResume={setResume} save={saveResume} busy={busy} API={API} token={token}/>} {error&&<pre className="card text-red-700 whitespace-pre-wrap">{error}</pre>}</section></div></main>
}
function Auth(p:Any){return <main className="min-h-screen grid place-items-center bg-neutral-50"><div className="card w-full max-w-md"><h1 className="text-3xl font-bold">CVForge</h1><p className="text-neutral-500 mt-2">Production-grade, evidence-first resume tailoring.</p>{p.mode==="register"&&<input className="input mt-6" placeholder="Name" value={p.name} onChange={(e:any)=>p.setName(e.target.value)}/>}<input className="input mt-3" placeholder="Email" value={p.email} onChange={(e:any)=>p.setEmail(e.target.value)}/><input className="input mt-3" type="password" placeholder="Password" value={p.password} onChange={(e:any)=>p.setPassword(e.target.value)}/><button className="btn w-full mt-4" onClick={p.submit}>{p.mode==="login"?"Sign in":"Create account"}</button><button className="text-sm mt-4 underline" onClick={()=>p.setMode(p.mode==="login"?"register":"login")}>{p.mode==="login"?"Create an account":"I already have an account"}</button>{p.error&&<pre className="text-red-600 whitespace-pre-wrap mt-4">{p.error}</pre>}</div></main>}
function Editor({resume,setResume,save,busy,API,token}:Any){const r=resume.resume;const set=(k:string,v:any)=>setResume({...resume,resume:{...r,[k]:v}});return <div className="card"><div className="flex justify-between items-center"><div><h2 className="text-xl font-semibold">Resume editor</h2><p className="text-xs text-neutral-500">Revision {resume.version} · edit evidence-derived content before export.</p></div><div className="flex gap-2"><button className="btn" onClick={save} disabled={busy}>Save revision</button><a className="btn" href={`${API}/api/v1/resumes/${resume.id}/download?format=docx`} target="_blank">DOCX</a><a className="btn dark" href={`${API}/api/v1/resumes/${resume.id}/download?format=pdf`} target="_blank">PDF</a></div></div><div className="mt-6 grid lg:grid-cols-2 gap-6"><div><label className="label">Headline</label><input className="input" value={r.headline||""} onChange={e=>set("headline",e.target.value)}/><label className="label mt-4">Summary</label><textarea className="input min-h-40" value={r.summary||""} onChange={e=>set("summary",e.target.value)}/><label className="label mt-4">Skills — comma separated</label><input className="input" value={(r.skills||[]).join(", ")} onChange={e=>set("skills",e.target.value.split(",").map((x:string)=>x.trim()).filter(Boolean))}/></div><div className="border rounded-xl p-6 bg-white"><h1 className="text-2xl font-bold">{r.name}</h1><p className="text-sm">{r.contact_line}</p><p className="font-medium mt-2">{r.headline}</p><h3 className="section">Summary</h3><p className="text-sm leading-6">{r.summary}</p><h3 className="section">Skills</h3><p className="text-sm">{(r.skills||[]).join(" · ")}</p>{(r.experience||[]).map((e:Any,i:number)=><div key={i} className="mt-5"><b>{e.title} — {e.company}</b>{(e.bullets||[]).map((b:string,j:number)=><p key={j} className="text-sm mt-1">• {b}</p>)}</div>)}</div></div></div>}
