"""saas product layer
Revision ID: 0002_saas_product
Revises: 0001_initial
"""
from alembic import op
import sqlalchemy as sa
revision='0002_saas_product'; down_revision='0001_initial'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('users',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('email',sa.String(320),nullable=False),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('name',sa.String(255),nullable=False,server_default=''),sa.Column('created_at',sa.DateTime(),nullable=False));op.create_index('ix_users_email','users',['email'],unique=True)
    op.create_table('candidate_profiles',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('name',sa.String(255),nullable=False),sa.Column('profile_json',sa.JSON(),nullable=False),sa.Column('source_text',sa.Text(),nullable=False),sa.Column('is_default',sa.Boolean(),nullable=False,server_default=sa.text('false')),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False));op.create_index('ix_candidate_profiles_user_id','candidate_profiles',['user_id'])
    op.create_table('applications',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('candidate_profile_id',sa.Integer(),sa.ForeignKey('candidate_profiles.id'),nullable=True),sa.Column('job_title',sa.String(255),nullable=False),sa.Column('company',sa.String(255),nullable=False),sa.Column('job_json',sa.JSON(),nullable=False),sa.Column('status',sa.String(40),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False));op.create_index('ix_applications_user_id','applications',['user_id']);op.create_index('ix_applications_status','applications',['status'])
    op.create_table('prompt_versions',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('prompt_key',sa.String(255),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('prompt_text',sa.Text(),nullable=False),sa.Column('role_family',sa.String(80),nullable=False),sa.Column('seniority',sa.String(80),nullable=False),sa.Column('domain',sa.String(80),nullable=False),sa.Column('active',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False));op.create_index('ix_prompt_versions_prompt_key','prompt_versions',['prompt_key'])
    op.add_column('generation_jobs',sa.Column('application_id',sa.Integer(),sa.ForeignKey('applications.id'),nullable=True));op.add_column('generation_jobs',sa.Column('input_json',sa.JSON()));op.add_column('generation_jobs',sa.Column('error',sa.Text()));op.add_column('generation_jobs',sa.Column('attempts',sa.Integer(),nullable=False,server_default='0'));op.add_column('generation_jobs',sa.Column('started_at',sa.DateTime()));op.add_column('generation_jobs',sa.Column('finished_at',sa.DateTime()));op.create_index('ix_generation_jobs_application_id','generation_jobs',['application_id']);op.create_index('ix_generation_jobs_status','generation_jobs',['status'])
    op.alter_column('generation_jobs','status',server_default='queued');op.add_column('resume_artifacts',sa.Column('application_id',sa.Integer(),sa.ForeignKey('applications.id'),nullable=True));op.alter_column('resume_artifacts','job_id',nullable=True);op.add_column('resume_artifacts',sa.Column('version',sa.Integer(),nullable=False,server_default='1'));op.add_column('resume_artifacts',sa.Column('prompt_version_id',sa.Integer(),sa.ForeignKey('prompt_versions.id')));op.add_column('resume_artifacts',sa.Column('template_key',sa.String(120),nullable=False,server_default='classic_ats'));op.create_index('ix_resume_artifacts_application_id','resume_artifacts',['application_id'])
    op.create_table('generation_events',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('generation_job_id',sa.Integer(),sa.ForeignKey('generation_jobs.id'),nullable=False),sa.Column('event_type',sa.String(80),nullable=False),sa.Column('payload',sa.JSON()),sa.Column('created_at',sa.DateTime(),nullable=False));op.create_index('ix_generation_events_generation_job_id','generation_events',['generation_job_id'])

def downgrade(): raise NotImplementedError()
